// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatitasFelices.BD.Data;

#nullable disable

namespace PatitasFelices.BD.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComentarioId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaPublicacion")
                        .HasColumnType("date");

                    b.Property<string>("TextoComentario")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioAutoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioDestinatarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ComentarioId" }, "ComentarioId_UQ")
                        .IsUnique();

                    b.HasIndex(new[] { "TextoComentario", "FechaPublicacion" }, "TextoComentario_FechaPublicacion");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.Foto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FotoId")
                        .HasColumnType("int");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FotoId" }, "FotoId_UQ")
                        .IsUnique();

                    b.HasIndex(new[] { "UrlFoto", "Descripcion" }, "UrlFoto_Descripcion");

                    b.ToTable("Foto");
                });

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.FotoMascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FotoMascotaId")
                        .HasColumnType("int");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FotoMascotaId" }, "FotoMascotaId_UQ")
                        .IsUnique();

                    b.HasIndex(new[] { "UrlFoto", "Descripcion" }, "UrlFoto_Descripcion");

                    b.ToTable("FotoMascota");
                });

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.FotoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FotoUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("UrlFoto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FotoUsuarioId" }, "FotoUsuarioId_UQ")
                        .IsUnique();

                    b.HasIndex(new[] { "UrlFoto", "Descripcion" }, "UrlFoto_Descripcion");

                    b.ToTable("FotoUsuario");
                });

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.Mascota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<string>("NecesidadesEspeciales")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Raza")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tamaño")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MascotaId" }, "MascotaId_UQ")
                        .IsUnique();

                    b.HasIndex(new[] { "Nombre", "Raza", "Edad", "Tamaño", "Foto", "NecesidadesEspeciales" }, "Nombre_Raza_Edad_Tamaño_Foto_NecesidadesEspeciales");

                    b.ToTable("Mascota");
                });

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoMensaje")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaHoraMensaje")
                        .HasColumnType("datetime2");

                    b.Property<int>("MensajeId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioEmisorId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioReceptorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ContenidoMensaje", "FechaHoraMensaje" }, "ContenidoMensaje_FechaHoraMensaje");

                    b.HasIndex(new[] { "MensajeId" }, "MensajeId_UQ")
                        .IsUnique();

                    b.ToTable("Mensaje");
                });

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.NombreServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreDeServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrecioServicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NombreDeServicio", "Precio" }, "NombreDeServicio_Precio");

                    b.HasIndex(new[] { "PrecioServicioId" }, "PrecioServicioId_UQ")
                        .IsUnique();

                    b.ToTable("NombreServicio");
                });

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.Precio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrecioDia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrecioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "PrecioHora", "PrecioDia" }, "PrecioHora_PrecioDia");

                    b.HasIndex(new[] { "PrecioId" }, "PrecioId_UQ")
                        .IsUnique();

                    b.ToTable("Precio");
                });

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.PrecioServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrecioServicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NombreServicio", "Precio" }, "NombreServicio_Precio");

                    b.HasIndex(new[] { "PrecioServicioId" }, "PrecioServicioId_UQ")
                        .IsUnique();

                    b.ToTable("PrecioServicio");
                });

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstadoReserva")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MascotaId")
                        .HasColumnType("int");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FechaHoraInicio", "FechaHoraFin", "EstadoReserva" }, "FechaHoraInicio_FechaHoraFin_EstadoReserva");

                    b.HasIndex(new[] { "ReservaId" }, "ReservaId_UQ")
                        .IsUnique();

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NombreServicio" }, "NombreServicio");

                    b.HasIndex(new[] { "ServicioId" }, "ServicioId_UQ")
                        .IsUnique();

                    b.ToTable("Servicio");
                });

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.Tarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoSeguridad")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<string>("NroTarjeta")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("TarjetaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "FechaVencimiento", "CodigoSeguridad" }, "Fecha_CodigoSeguridad");

                    b.HasIndex(new[] { "TarjetaId" }, "TarjetaId_UQ")
                        .IsUnique();

                    b.ToTable("Tarjeta");
                });

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int");

                    b.Property<int>("TarjetaId")
                        .HasColumnType("int");

                    b.Property<int>("TransaccionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Monto", "MetodoPago" }, "Monto_MetodoPago");

                    b.HasIndex(new[] { "TransaccionId" }, "TransaccionId_UQ")
                        .IsUnique();

                    b.ToTable("Transaccion");
                });

            modelBuilder.Entity("PatitasFelices.BD.Data.Entity.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CorreoElectronico_Usuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
